"""The build protocol (DESIGN §8.2): arms, variant builds, caching and verification.

placemat runs the project's build command once per pad of each arm (data settings need no rebuild),
and once for the stock build, with this environment:

    PLACEMAT_SRC          the arm's source tree (read it; don't build in it)
    PLACEMAT_OUT          a fresh directory; leave the binary at PLACEMAT_OUT/<build.binary>
    PLACEMAT_WORK         a directory kept between builds of this arm (for incremental builds)
    PLACEMAT_VARIANT      a tag: 'stock', or 'p<bytes>' plus '-h' when hooked
    PLACEMAT_PAD          the pad's size in bytes (unset for the stock build)
    PLACEMAT_PAD_SOURCE   a generated C file holding the pad function (unset for the stock build):
                          compile it into the first object linked, or link it first
    PLACEMAT_HOOK         1 when the build should include the data hook (placemat.h, -DPLACEMAT_HOOK)
    PLACEMAT_INCLUDE      the directory holding placemat.h
    PLACEMAT_CFLAGS       flags to add to every compile (-DPLACEMAT_HOOK -I... when hooked)
    PLACEMAT_LDFLAGS      flags to add to the link
    PLACEMAT_ORDER_FILE   for a pinned arm: the linker order file to link with (in the platform's style;
                          with --pad-first its first entry is the pad, so the code axis moves the whole
                          ordered region: P009's comparison of ordering strategies)
    PLACEMAT_PIN_SOURCE   for a pinned arm: a C file of pad functions named in the order file (placemat pin pads;
                          with --pin, planned afresh for this build after a first link without them)
    PLACEMAT_ALIGN        for a pinned arm: the function alignment the pin pads assume (compile with
                          -falign-functions=$PLACEMAT_ALIGN); placemat checks the ordered placement after linking

An arm is a git revision of the project ('git:<rev>', exported once with git archive) or a source
directory. Builds are cached by the arm's tree id and the variant tag. The tree id covers the arm's
source (the revision, or the files matching `[build] inputs`), the build command and environment, the
adapter's scripts (the config directory's .py/.sh/.h/.c files, every file the build command names by
path with the like files beside it, and `[build] inputs` patterns that start with {config_dir} or
{root}), placemat's data sources, and the platform the build runs on (OS and architecture, of the
`[target]` when one is set, with its prefix). Every variant is verified after linking: the pad function
must be present (it can be dead-stripped despite `used`). A pinned arm's ELF links get
`-Wl,-z,separate-code` in PLACEMAT_LDFLAGS (so read-only sections growing with the pin pads' unwind
info cannot move .text), and a build whose pin pads were planned by placemat (`--pin`) must land where
the plan put them: otherwise the build fails.
"""
from __future__ import annotations

import fcntl
import hashlib
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .config import Config

PAD_SYMBOL = "placemat_pad"


@dataclass
class Arm:
    name: str
    source: str          # 'git:<rev>' or a directory
    dir: Path            # the tree the build reads and the benchmarks run from
    tree: str            # cache key
    order: Path | None = None        # a pinned arm's order file
    pin_source: Path | None = None   # its pad functions
    pad_first: bool = False          # list the code-axis pad first in the order file
    pin_order: Path | None = None    # replan the pin pads for every build from this order (no pads in it)
    pin_spans: Path | None = None    # hot entry spans for that planning (JSON)


def pad_source(n: int) -> str:
    return ("/* generated by placemat: a code-layout pad (DESIGN 5.2) */\n"
            f"__attribute__((used)) static void {PAD_SYMBOL}(void){{__asm__ volatile(\".space {n}\");}}\n")


ADAPTER_SUFFIXES = (".py", ".sh", ".h", ".c")


def _hash_inputs(d: Path, globs: list[str]) -> str:
    h = hashlib.sha1()
    files = sorted({f for g in globs if not (Path(g).is_absolute() or g.startswith("{"))   # {config_dir}/...:
                    for f in d.glob(g) if f.is_file()})                                    # in cache_key
    for f in files:
        h.update(str(f.relative_to(d)).encode() + b"\0" + f.read_bytes())
    return h.hexdigest()[:12]


def _expanded(cfg: Config, x: str) -> str | None:
    """x with {config_dir} and {root} filled in; None when it names the arm (or anything else per build)."""
    try:
        return cfg.expand(x)
    except (KeyError, IndexError, ValueError):
        return None


def adapter_files(cfg: Config) -> list[Path]:
    """The files outside the arm's tree that its builds depend on: the config directory's adapter scripts
    (.py/.sh/.h/.c), every file the build command names by path (absolute, or relative to the project
    root where the command runs; also after an '=' as in --script=PATH) with the adapter scripts beside it
    (a harness next to a build script in a parent directory, say), and the files matching `[build] inputs`
    patterns that start with {config_dir} or {root} (relative patterns name files in the arm's tree)."""
    import glob as _glob
    out: set[Path] = set()

    def scripts_in(d: Path):
        if d.is_dir():
            out.update(f.resolve() for f in d.iterdir() if f.is_file() and f.suffix in ADAPTER_SUFFIXES)

    scripts_in(cfg.config_dir)
    for x in cfg.build_command:
        e = _expanded(cfg, x)
        if not e:
            continue
        for v in {e, e.rsplit("=", 1)[-1]}:
            if not v or "\n" in v or len(v) > 4096:
                continue
            p = Path(v) if Path(v).is_absolute() else cfg.root / v
            try:
                if p.is_file():
                    out.add(p.resolve())
                    scripts_in(p.resolve().parent)
            except OSError:
                pass
    for g in cfg.inputs:
        if "{" in g and (e := _expanded(cfg, g)) and Path(e).is_absolute():
            out.update(Path(f).resolve() for f in _glob.glob(e, recursive=True) if Path(f).is_file())
    return sorted(out)


_PLATFORMS: dict[tuple, str] = {}


def build_platform(cfg: Config) -> str:
    """Where builds run: 'Darwin arm64', say, or with a [target] its prefix and the target's `uname -sm`
    ('?' when the target cannot be asked: a key that differs, so nothing stale is reused)."""
    import platform as _platform
    pre = tuple(cfg.target_prefix)
    if not pre:
        return f"{_platform.system()} {_platform.machine()}"
    if pre not in _PLATFORMS:
        try:
            r = subprocess.run(list(pre) + ["uname", "-sm"], capture_output=True, text=True, timeout=120)
            un = r.stdout.strip() if not r.returncode and r.stdout.strip() else "?"
        except (OSError, subprocess.TimeoutExpired):
            un = "?"
        _PLATFORMS[pre] = f"target {' '.join(pre)}: {un}"
    return _PLATFORMS[pre]


def cache_key(cfg: Config) -> str:
    """The part of every arm's cache key that is not the arm's own source (see the module docstring)."""
    h = hashlib.sha1(repr(sorted(cfg.build_env.items())).encode() + " ".join(cfg.build_command).encode())
    for f in adapter_files(cfg):                   # the project's adapter scripts (a hook patcher, say)
        try:
            name = os.path.relpath(f, cfg.config_dir)
        except ValueError:
            name = str(f)
        h.update(name.encode() + b"\0" + f.read_bytes())
    for f in sorted(header_dir().glob("*")):      # placemat's own hook header goes into hooked builds
        if f.is_file() and f.suffix in (".h", ".c"):
            h.update(f.name.encode() + b"\0" + f.read_bytes())
    h.update(b"\0platform\0" + build_platform(cfg).encode())
    return h.hexdigest()[:6]


class Builder:
    def __init__(self, cfg: Config, work: Path):
        self.cfg, self.work = cfg, work
        (work / "bin").mkdir(parents=True, exist_ok=True)
        self.envtag = cache_key(cfg)
        self.platform = build_platform(cfg)
        self.fmt = "macho" if ("Darwin" in self.platform) else "elf"    # the binaries' format, for order files
        self.warnings: list[str] = []

    # ---- arms ------------------------------------------------------------------------------------

    def arm(self, name: str, source: str, order: str | None = None, pin_source: str | None = None,
            pad_first: bool = False, pin_order: str | None = None, pin_spans: str | None = None) -> Arm:
        """An arm; pinned with fixed pin pads (`order`, `pin_source`) or with pin pads planned afresh for
        every build (`pin_order`, `pin_spans`: each build at its own position, DESIGN §6.3 step 7).
        `pad_first` (the code-axis pad listed first, so the ordered region moves) applies to padded builds."""
        a = self._arm(name, source)
        if order or pin_source or pin_order:
            h = hashlib.sha1(b"replan" if pin_order else b"")
            for f in (order, pin_source, pin_order, pin_spans):
                h.update(b"\0" + (Path(f).read_bytes() if f else b""))
            h.update(str(self.cfg.pin_align).encode())
            a.order = Path(order).resolve() if order else None
            a.pin_source = Path(pin_source).resolve() if pin_source else None
            a.pin_order = Path(pin_order).resolve() if pin_order else None
            a.pin_spans = Path(pin_spans).resolve() if pin_spans else None
            a.tree += "-o" + h.hexdigest()[:8]
        a.pad_first = pad_first
        return a

    def _arm(self, name: str, source: str) -> Arm:
        if source.startswith("git:") or not Path(source).is_dir():
            rev = source[4:] if source.startswith("git:") else source
            sha = subprocess.run(["git", "-C", str(self.cfg.root), "rev-parse", rev + "^{commit}"],
                                 capture_output=True, text=True)
            if sha.returncode:
                sys.exit(f"placemat: arm {name}: {source!r} is neither a directory nor a git revision")
            sha = sha.stdout.strip()
            d = self.work / "src" / sha[:12]
            if not (d / ".placemat-exported").exists():
                if d.exists():
                    shutil.rmtree(d)
                d.mkdir(parents=True)
                a = subprocess.run(["git", "-C", str(self.cfg.root), "archive", sha], capture_output=True, check=True).stdout
                subprocess.run(["tar", "-x", "-C", str(d)], input=a, check=True)
                (d / ".placemat-exported").write_text(sha + "\n")
            return Arm(name, f"git:{sha}", d, sha[:12] + "-" + self.envtag)
        d = Path(source).resolve()
        return Arm(name, str(d), d, "d" + _hash_inputs(d, self.cfg.inputs) + "-" + self.envtag)

    # ---- variants --------------------------------------------------------------------------------

    def binary(self, arm: Arm, pad: int | None, hooked: bool = False) -> Path:
        """The binary of `arm` with a pad of `pad` bytes (None: the stock build, no pad and no hook)."""
        tag = "stock" if pad is None else f"p{pad}" + ("-h" if hooked else "") + ("-pf" if arm.pad_first else "")
        out = self.work / "bin" / arm.tree / tag     # (-pf only on padded builds: an unpadded build is the same either way)
        b = out / Path(self.cfg.binary).name
        if b.exists():
            return b
        locks = self.work / "locks"
        locks.mkdir(exist_ok=True)
        with open(locks / f"{arm.tree}-{tag}.lock", "a") as lk:   # placemat processes sharing a work directory
            fcntl.flock(lk, fcntl.LOCK_EX)
            if b.exists():
                return b
            return self._build(arm, pad, hooked, tag, out, b)

    def _build(self, arm: Arm, pad: int | None, hooked: bool, tag: str, out: Path, b: Path) -> Path:
        from .binary import link_name, read_order
        fmt = self.fmt
        lead = [link_name(fmt, PAD_SYMBOL)] if arm.pad_first and pad is not None else []
        plan = None
        if arm.pin_order:                              # replan: link without pin pads, plan at this position, relink
            base = [n for n in read_order(arm.pin_order, fmt)]
            first = self._link(arm, pad, hooked, tag + "-plan", lead + [link_name(fmt, n) for n in base], None)
            from .pin.pads import pad_source as pin_pad_source, pads as plan_pads
            plan = plan_pads(first, base, boundary=self.cfg.boundary, align=self.cfg.pin_align,
                             spans=str(arm.pin_spans) if arm.pin_spans else None)
            built = self._link(arm, pad, hooked, tag, lead + [link_name(fmt, n) for n in plan.order()],
                               pin_pad_source(plan, f"planned for {arm.name} {tag}"))
            shutil.rmtree(self.work / "build" / f"{arm.tree}-{tag}-plan", ignore_errors=True)
            if plan.loop_crossings or plan.span_crossings:
                self.warnings.append(f"{arm.name} {tag}: pin pads left {len(plan.loop_crossings)} loop and "
                                     f"{len(plan.span_crossings)} span crossings")
        elif arm.order:
            built = self._link(arm, pad, hooked, tag, lead + arm.order.read_text().splitlines(),
                               arm.pin_source.read_text() if arm.pin_source else None)
        else:
            built = self._link(arm, pad, hooked, tag, None, None)
        if pad is not None:
            syms = nm_symbols(built)
            if PAD_SYMBOL not in syms:
                sys.exit(f"placemat: build of {arm.name} {tag}: no {PAD_SYMBOL} in {built} (dead-stripped? not linked?)")
            a0 = syms[PAD_SYMBOL]
            after = [v for v in syms.values() if v > a0]
            if not after or min(after) - a0 < pad:     # the code after the pad must start at least its size later
                self.warnings.append(f"{arm.name} {tag}: the next function starts {min(after) - a0 if after else 0} B "
                                     f"after {PAD_SYMBOL}, less than the pad's {pad} B: the pad may not move the code")
            elif sum(1 for v in syms.values() if v < a0) > max(16, len(syms) // 4):
                self.warnings.append(f"{arm.name} {tag}: {sum(1 for v in syms.values() if v < a0)} of {len(syms)} "
                                     f"functions precede {PAD_SYMBOL}: is it linked first?")
        if arm.order or arm.pin_order:                 # a pinned arm: are the ordered functions where they should be?
            try:
                from .pin.verify import verify
                rep = verify(built, str(built.parent / "placemat.order"), align=self.cfg.pin_align, plan=plan)
            except Exception as e:                     # a verification failure must not lose a build
                rep = None
                self.warnings.append(f"{arm.name} {tag}: could not verify the pinned placement ({e})")
            if rep is not None and rep.misplaced:      # pin pads planned for addresses the code did not get
                sys.exit(misplaced_message(f"{arm.name} {tag}", rep, built, self.fmt, plan.boundary))
            if rep is not None and (rep.missing or rep.out_of_order or rep.gaps or rep.misaligned):
                self.warnings.append(f"{arm.name} {tag}: pinned placement not as ordered: "
                                     + "; ".join(l for l in rep.lines()[1:4]))
        out.mkdir(parents=True, exist_ok=True)
        shutil.copy2(built, b)
        shutil.rmtree(self.work / "build" / f"{arm.tree}-{tag}", ignore_errors=True)
        return b

    def _cc_env(self) -> dict:
        d = self.work / "cc"
        return {"CC": str(_shim(d / "placemat-cc", False)), "CXX": str(_shim(d / "placemat-cxx", True)),
                "PLACEMAT_REAL_CC": os.environ.get("CC", "cc"), "PLACEMAT_REAL_CXX": os.environ.get("CXX", "c++")}

    def _link(self, arm: Arm, pad: int | None, hooked: bool, tag: str, order_lines: list[str] | None,
              pin_c: str | None) -> Path:
        """One run of the project's build command; the binary it left, in a fresh directory."""
        tmp = self.work / "build" / f"{arm.tree}-{tag}"
        if tmp.exists():
            shutil.rmtree(tmp)
        tmp.mkdir(parents=True)
        keep = self.work / "keep" / arm.tree
        keep.mkdir(parents=True, exist_ok=True)
        env = {**os.environ, **self.cfg.build_env, "PLACEMAT_SRC": str(arm.dir), "PLACEMAT_OUT": str(tmp),
               "PLACEMAT_WORK": str(keep), "PLACEMAT_VARIANT": tag, "PLACEMAT_INCLUDE": str(header_dir()),
               "PLACEMAT_CFLAGS": "", "PLACEMAT_LDFLAGS": ""}
        for k in ("PLACEMAT_PAD", "PLACEMAT_PAD_SOURCE", "PLACEMAT_HOOK", "PLACEMAT_ORDER_FILE",
                  "PLACEMAT_PIN_SOURCE", "PLACEMAT_ALIGN"):
            env.pop(k, None)
        if pad is not None:
            ps = tmp / "placemat_pad.c"
            ps.write_text(pad_source(pad))
            env.update(PLACEMAT_PAD=str(pad), PLACEMAT_PAD_SOURCE=str(ps))
        if order_lines is not None:
            of = tmp / "placemat.order"
            of.write_text("\n".join(order_lines) + "\n")
            env["PLACEMAT_ORDER_FILE"] = str(of)
            env["PLACEMAT_ALIGN"] = str(self.cfg.pin_align)   # the function alignment the pin pads assume
            if self.fmt == "elf":                  # .text on its own pages: read-only sections before it cannot move it
                env["PLACEMAT_LDFLAGS"] = SEPARATE_CODE
        if pin_c is not None:
            pc = tmp / "placemat_pin_pads.c"
            pc.write_text(pin_c)
            env["PLACEMAT_PIN_SOURCE"] = str(pc)
        if hooked:
            env.update(PLACEMAT_HOOK="1", PLACEMAT_CFLAGS=f"-DPLACEMAT_HOOK -I{header_dir()}")
        cmd = [self.cfg.expand(x, arm_dir=arm.dir) for x in self.cfg.build_command]
        from .config import on_target
        if self.cfg.build_mode == "cc":                 # route 1: the compiler wrapper, in a copy of the tree
            tree = keep / ("tree-h" if hooked else "tree")
            if not tree.exists():
                shutil.copytree(arm.dir, tree, symlinks=True, ignore=shutil.ignore_patterns(".git", ".placemat"))
            env.update(self._cc_env())
            (tree / self.cfg.binary).unlink(missing_ok=True)     # so the build relinks
            lk = open(keep / ".tree.lock", "a")
            fcntl.flock(lk, fcntl.LOCK_EX)
            try:
                tcmd, tenv, tcwd = on_target(self.cfg, cmd, env, tree)
                r = subprocess.run(tcmd, cwd=tcwd, env=tenv, capture_output=True, text=True)
                if not r.returncode and (tree / self.cfg.binary).exists():
                    (tmp / self.cfg.binary).parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(tree / self.cfg.binary, tmp / self.cfg.binary)
            finally:
                lk.close()
        else:
            tcmd, tenv, tcwd = on_target(self.cfg, cmd, env, self.cfg.root)
            r = subprocess.run(tcmd, cwd=tcwd, env=tenv, capture_output=True, text=True)
        built = tmp / self.cfg.binary
        if r.returncode or not built.exists():
            sys.exit(f"placemat: build of {arm.name} {tag} failed ({' '.join(cmd)}):\n{r.stdout[-3000:]}{r.stderr[-3000:]}")
        if order_lines is not None and built.parent != tmp:
            shutil.copy2(of, built.parent / "placemat.order")
        return built

SEPARATE_CODE = "-Wl,-z,separate-code"


def misplaced_message(what: str, rep, built: Path, fmt: str, boundary: int) -> str:
    """The error for a pinned build whose functions are not where its pin pads were planned."""
    shifts = sorted({(x - p) % boundary for _, x, p in rep.misplaced})
    sh = shifts[0] if shifts[0] <= boundary // 2 else shifts[0] - boundary
    moved = (f"the whole ordered region moved by {sh:+d} bytes (mod {boundary}) between the planning "
             "link and the final one" if len(shifts) == 1 and len(rep.misplaced) == rep.listed_planned else
             f"{len(rep.misplaced)} of {rep.listed_planned} planned functions landed elsewhere")
    why = ("something linked before the region changed size: on ELF, read-only sections placed before .text "
           "(.eh_frame, .rodata) grow with the pin pads' unwind info and data. placemat passes "
           f"{SEPARATE_CODE} in PLACEMAT_LDFLAGS for pinned ELF links: make sure the build adds $PLACEMAT_LDFLAGS "
           "to its link command (and that the linker honours it: GNU ld 2.31+, lld)" if fmt == "elf" else
           "something linked before the region changed size, or the linker did not keep the functions' "
           "alignment (set [build] pin_align to what it preserves)")
    return (f"placemat: build of {what}: the pinned functions are not where their pin pads were planned: {moved}; "
            f"{why}. The pin pads do not protect this build, so it is not used. Placement check of {built}:\n  "
            + "\n  ".join(rep.lines()[1:12]))


def _shim(path: Path, cxx: bool) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    root = Path(__file__).resolve().parent.parent
    path.write_text("#!/bin/sh\n" + ("PLACEMAT_CC_MODE=cxx; export PLACEMAT_CC_MODE\n" if cxx else "")
                    + f'PYTHONPATH={shlex_quote(str(root))}${{PYTHONPATH:+:$PYTHONPATH}} exec {shlex_quote(sys.executable)} -m placemat.cc "$@"\n')
    path.chmod(0o755)
    return path


def shlex_quote(s: str) -> str:
    import shlex
    return shlex.quote(s)


def header_dir() -> Path:
    try:
        from .cbuild import header_dir as hd
        return hd()
    except ImportError:
        return Path(__file__).parent / "data"


def nm_symbols(b: Path) -> dict[str, int]:
    """Text symbols -> address, names as nm prints them less a Mach-O leading underscore."""
    d = {}
    r = subprocess.run(["nm", "-n", str(b)], capture_output=True, text=True)
    macho = _is_macho(b)
    for l in r.stdout.splitlines():
        p = l.split()
        if len(p) == 3 and p[1] in "tT":
            if p[2] in MACHO_HEADER_SYMBOLS:          # the Mach-O header: a T symbol at the segment start, not code
                continue
            n = p[2][1:] if macho and p[2].startswith("_") else p[2]
            d.setdefault(n, int(p[0], 16))
    return d


def _is_macho(b: Path) -> bool:
    try:
        with open(b, "rb") as f:
            return f.read(4) in (b"\xcf\xfa\xed\xfe", b"\xca\xfe\xba\xbe")
    except OSError:
        return sys.platform == "darwin"


# nm lists the Mach-O header as a text symbol (at __TEXT's start, before any code): never "the first text symbol"
MACHO_HEADER_SYMBOLS = ("__mh_execute_header", "__mh_dylib_header", "__mh_bundle_header", "_mh_execute_header")


def has_symbol(b: Path, name: str) -> bool:
    return name in nm_symbols(b)


def shifts(ref: Path, b: Path) -> tuple[int, float, int]:
    """(the most common shift of a function against ref, the share of functions not moved, functions)."""
    import collections
    a, c = nm_symbols(ref), nm_symbols(b)
    common = [k for k in a if k in c and k != PAD_SYMBOL]
    after = [k for k in common if PAD_SYMBOL not in a or a[k] > a[PAD_SYMBOL]]
    # the shift: the most common move of what follows the pad (on ELF the C runtime and .text.startup come
    # first and do not move); the unmoved share: over all functions, so a pinned region placed before the
    # pad by an order file counts as unmoved
    s = collections.Counter(c[k] - a[k] for k in after)
    n = len(common)
    unmoved = sum(1 for k in common if c[k] == a[k])
    return (s.most_common(1)[0][0] if s else 0), (unmoved / n if n else 0.0), n
