/* prototype: pad functions placed between the hot functions by the order file (of/tools/pads.py) */
__attribute__((used)) void am_of_pad_1(void){__asm__ volatile(".space 1296");}
__attribute__((used)) void am_of_pad_2(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_3(void){__asm__ volatile(".space 32");}
__attribute__((used)) void am_of_pad_4(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_5(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_6(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_7(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_8(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_9(void){__asm__ volatile(".space 32");}
__attribute__((used)) void am_of_pad_10(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_11(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_12(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_13(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_14(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_15(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_16(void){__asm__ volatile(".space 96");}
__attribute__((used)) void am_of_pad_17(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_18(void){__asm__ volatile(".space 32");}
__attribute__((used)) void am_of_pad_19(void){__asm__ volatile(".space 80");}
__attribute__((used)) void am_of_pad_20(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_21(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_22(void){__asm__ volatile(".space 32");}
__attribute__((used)) void am_of_pad_23(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_24(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_25(void){__asm__ volatile(".space 224");}
__attribute__((used)) void am_of_pad_26(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_27(void){__asm__ volatile(".space 80");}
__attribute__((used)) void am_of_pad_28(void){__asm__ volatile(".space 48");}
__attribute__((used)) void am_of_pad_29(void){__asm__ volatile(".space 176");}
__attribute__((used)) void am_of_pad_30(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_31(void){__asm__ volatile(".space 160");}
__attribute__((used)) void am_of_pad_32(void){__asm__ volatile(".space 16");}
__attribute__((used)) void am_of_pad_33(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_34(void){__asm__ volatile(".space 480");}
__attribute__((used)) void am_of_pad_35(void){__asm__ volatile(".space 0");}
__attribute__((used)) void am_of_pad_36(void){__asm__ volatile(".space 0");}
